0.4.1
unstoppabledomains/uns pull request #109
Opened 2022-04-14 18:15 UTC by sudoryan

New release to include change that removes unused ELA versions

2022-04-14 18:21 UTC, aquiladev requested changes
these changes are not required, if you do not plan to release new tag

2022-04-14 18:21 UTC, aquiladev commented on contracts/UNSRegistry.sol
> +    string public constant VERSION = '0.4.1';
no need to change the version

2022-04-14 18:21 UTC, aquiladev commented on uns-config.json
> +    "version": "0.4.1",
no need to change the version

2022-04-14 18:24 UTC, sudoryan commented
I guess I don't understand how the tag system works on this repo. I'd like to be able to use the updated resolver-keys.json on the website. Are these changes already included in v0.4.0 or do I need to create a new tag and bump the version in the website?

2022-04-17 08:22 UTC, aquiladev approved these changes
ok, then these changes are needed.
there is the process:
1. merge changes with version update to the master
1. create and push new tag
  ```
  git tag v0.4.1
  git push origin --tags
  ```
3. update **uns** package with new tag on website
  ```
  yarn remove uns 
  yarn add https://github.com/unstoppabledomains/uns#v0.4.1
  ```

2022-04-26 08:46 UTC, merged