WIP: [REG-594]: Update MintingManager and UNSRegistry contracts to issue subdomains
unstoppabledomains/uns pull request #169
Opened 2022-09-28 09:36 UTC by altur-rang

2022-10-07 12:45 UTC, bogdan commented on contracts/IRegistryReader.sol
> +    function childIdOf(string[] calldata labels) external view returns (uint256);
Method name feels irrelevant now. Lets name it `namehash` or `tokenize` or your variant.

2022-10-07 12:45 UTC, bogdan commented on contracts/UNSRegistry.sol
> +        return tokenId;
As far as I understood, this function doesn't use `childIdOf` method because of calculation optimization. Please confirm if I am right. I am not sure this optimization makes sense at the cost of contract size.

2022-10-07 12:46 UTC, altur-rang commented on contracts/UNSRegistry.sol
> +        return tokenId;
Yes, it's for optimization. I will need to check the gas usage difference before making a final decision

2022-10-07 12:51 UTC, altur-rang commented on contracts/IRegistryReader.sol
> +    function childIdOf(string[] calldata labels) external view returns (uint256);
In this case, we need to update the ProxyReader

2022-10-10 14:51 UTC, bogdan commented on contracts/IRegistryReader.sol
> +    function childIdOf(string[] calldata labels) external view returns (uint256);
I think we just need its body to `ProxyReader` in case we want to maintain backward compatibility on that contract.

2022-10-11 13:12 UTC, aquiladev commented on contracts/IMintingManager.sol
> +    function safeIssueWithRecords(
I don't mind simplifying the interface while only we use it

2022-10-12 11:33 UTC, altur-rang commented on contracts/IRegistryReader.sol
> +    function childIdOf(string[] calldata labels) external view returns (uint256);
done

2022-10-12 12:09 UTC, altur-rang commented on contracts/IMintingManager.sol
> +    function safeIssueWithRecords(
@aquiladev does that mean we can also remove `safe*` functions ?

2022-10-13 12:46 UTC, bogdan commented on contracts/UNSRegistry.sol
> +    function _issue(
I can't find the code that suppose to transfer ownership of token from `MintingManager` to new owner in case domain was returned anywhere. Suppose it needs to be in this method.

2022-10-13 12:46 UTC, bogdan commented on contracts/MintingManager.sol
> +        require(_isTld(labels[labels.length - 1]), 'MintingManager: TLD_NOT_REGISTERED');
I believe this is no longer required as we are expecting a general permission check agains the owner of TLD for SLD minting.

2022-10-13 12:46 UTC, bogdan commented on contracts/MintingManager.sol
> +            unsRegistry.issue(to, labels);
I didn't find any check that would disallow `issue` call for TLD. So it means that we are not forcing anyone to register TLD via `addTld`. I think that is actually a good idea to issue all domains via `issue` or `issueWithRecords` even TLDs and perform all necessary checks and extra calls inside that method by checking `labels.length == ?`.

2022-10-13 12:50 UTC, altur-rang commented on contracts/UNSRegistry.sol
> +    function _issue(
Sure. It's on my list

2022-10-13 12:58 UTC, altur-rang commented on contracts/MintingManager.sol
> +            unsRegistry.issue(to, labels);
We have such validation: https://github.com/unstoppabledomains/uns/pull/169/files#diff-cdc48c829f224e0d366a982703433801e377ef56d1c2cebc64d74d5c5c41250aR65

If we want to mint a TLD via `issue`, we will need to update `onlyAllowed` to support both cases, and update `issue` to support additional logic for TLDs (`_addTld`). I'm concerned about this mess with supporting two different cases in the same function/modifier

2022-10-13 13:48 UTC, bogdan commented on contracts/MintingManager.sol
> +            unsRegistry.issue(to, labels);
I think it is a mess for contract but very pretty for client. Maybe it will also save some space on registry contract. @aquiladev what do you think about minting TLDs and SLDs via the same `issue` method and having all conditions inside?

2022-10-17 12:41 UTC, bogdan commented on contracts/UNSRegistry.sol
> +    function issue(address to, string[] calldata labels) external override {
I don't see permission check here. Is it right?

2022-10-17 12:41 UTC, bogdan commented on contracts/UNSRegistry.sol
>      ) external override onlyMintingManager {
According to our idea, `MintingManager` should not be the only way to issue subdomains. Domain owners may issue subdomains themselves. I believe that it is not possible with current design as there are exclusive to `MintingManager` methods on `UNSRegistry`. I think we should avoid that by limiting the scope of `issue` to `MintingManager` and have a `UNSRegistry#mint` with `onlyApprovedForOwner` check. The issuing of returned domains inside `MintingManager#issue` can be performed via `setOwner`, `setMany` or `safeTransferFrom` as they are default methods.

2022-10-18 10:14 UTC, altur-rang commented on contracts/UNSRegistry.sol
> +    function issue(address to, string[] calldata labels) external override {
We have it here: https://github.com/unstoppabledomains/uns/pull/169/files#diff-2778ac5d37a31570d87facb230465fad451da8de1de0673385bf70414a582148R352

2022-10-18 11:24 UTC, altur-rang commented on contracts/MintingManager.sol
> +        require(_isTld(labels[labels.length - 1]), 'MintingManager: TLD_NOT_REGISTERED');
We still need this one. If we will [remove](https://github.com/unstoppabledomains/uns/blob/main/contracts/MintingManager.sol#L86) TLD, token ownership still will be on MIntingManager and we will be able to mint such tokens

2022-10-19 11:36 UTC, bogdan commented on contracts/MintingManager.sol
> +        if (unsRegistry.exists(tokenId) && unsRegistry.ownerOf(tokenId) == address(this)) {
The error will be more readable if we require ownership instead of trying to mint token that is already minted.

```suggestion
        if (unsRegistry.exists(tokenId)) {
          require(unsRegistry.ownerOf(tokenId) == address(this), "MintingManager: ISSUING_UNOWNED_TOKEN")
```

2022-10-19 11:43 UTC, altur-rang commented on contracts/MintingManager.sol
> +        if (unsRegistry.exists(tokenId) && unsRegistry.ownerOf(tokenId) == address(this)) {
ownerOf doesn't return address if token doesn't exist:
<img width="650" alt="Screenshot 2022-10-19 at 2 43 07 PM" src="https://user-images.githubusercontent.com/108257463/196681415-742aa0c9-7c63-4828-986a-5ce2762f8dca.png">

2022-10-19 11:45 UTC, bogdan commented on contracts/MintingManager.sol
> +        if (unsRegistry.exists(tokenId) && unsRegistry.ownerOf(tokenId) == address(this)) {
It shouldn't be a problem as you check if it exists just one line above.

2022-10-21 11:25 UTC, nickshatilo commented on contracts/MintingManager.sol
> +        for (uint256 i = labels.length; i > 0; i--) node = _namehash(node, labels[i - 1]);
#minor Can we please add curly braces here to improve readability?

2022-10-21 13:00 UTC, bogdan requested changes

2022-10-21 13:00 UTC, bogdan commented on contracts/MintingManager.sol
> +            unsRegistry.setReverse(to, tokenId);
You need to ensure you don't override reverse if it is already set for `to` address.

Maybe it makes sense to name this method differently because it have different permission check and purpose. Maybe it even makes sense to combine `setReverse`, `setOwner` and `reconfigure` call for the gas usage purposes. @aquiladev what do you think?

2022-10-24 08:29 UTC, altur-rang commented on contracts/MintingManager.sol
> +            unsRegistry.setReverse(to, tokenId);
Is it pretty rare for the same user to buy same domain again, or are there other ways to get a reverse for returned domain ?

It will increase UNSRegistry contract size, are you okay with it ? I can check how much gas we can save if we create a separate function

2022-10-24 09:20 UTC, altur-rang commented on contracts/MintingManager.sol
> +            unsRegistry.setReverse(to, tokenId);
It will save 5302 gas and increase UNSRegistry contract by 0.084kb

2022-10-24 11:48 UTC, aquiladev commented on contracts/MintingManager.sol
> +            unsRegistry.setReverse(to, tokenId);
indeed we should not override reverse record when it is present. how about to move the responsibility to `setOwner`?
```
 function setOwner(address to, uint256 tokenId) external override onlyApprovedOrOwner(tokenId) protectTokenOperation(tokenId) {
     _transfer(ownerOf(tokenId), to, tokenId);
     _safeSetReverse(to, tokenId);
 }
```

2022-10-24 17:05 UTC, aquiladev commented on contracts/MintingManager.sol
> +            unsRegistry.setReverse(to, tokenId);
take a look my updates ->

2022-10-25 07:42 UTC, altur-rang commented on contracts/MintingManager.sol
> +            unsRegistry.setReverse(to, tokenId);
Looks great

2022-10-25 08:11 UTC, bogdan approved these changes

2022-10-25 12:19 UTC, bogdan approved these changes

2022-10-25 12:19 UTC, bogdan commented on contracts/UNSRegistry.sol
> +        _transfer(ownerOf(tokenId), to, tokenId);
It feels more logical to call `_transfer` and than `_reconfigure` than vice versa: there is no difference now but it might appear in the future.

2022-10-26 13:26 UTC, aquiladev approved these changes

2022-10-26 13:31 UTC, merged