[ECH-482] Remove ERC20, BEP20, and MATIC options for 0ZK
unstoppabledomains/uns pull request #184
Opened 2022-11-01 13:28 UTC by dgrishajev

## PR Checklist

### 1. Contracts versioning
- [ ] Make sure that the `patch` version of the contracts is increased if changes have been made to the `UNSRegistry`, `MintingManager` or `ProxyReader` contracts.
- [ ] Make sure that the `minor` version of the contracts is increased if breaking changes have been made to the `UNSRegistry`, `MintingManager` or `ProxyReader` contracts. It includes changes of interfaces.
### 2. Contracts licensing
- [ ] Make sure that no **SPDX-License-Identifier** defined in contracts.
- [ ] Make sure that the **header** is added to the new contract files. 
  ```
  // @author Unstoppable Domains, Inc.
  // @date {Month} {Day}(ordinal), {Year}
  ```
### 3. Coverage
- [ ] Make sure that the coverage of contracts has not decreased and strive **100%**
### 4. Configs versioning
- [ ] Make sure that the version of `uns-config.json` is increased if changes have been made to the config.
- [ ] Make sure that the version of `resolver-keys.json` is increased if changes have been made to the config.
### 5. Sandbox
- [ ] Make sure that the Sandbox is updated if changes have been made to contracts or deployment configuration.
  ```
  yarn rebuild:sandbox
  ```
### 6. Package versioning
- [ ] Make sure that the `patch` version of package is increased if valuable changes have been made to the package. It includes contracts update, configs update, etc.
- [ ] Make sure that the `major.minor` version of package is synced with version of `UNSRegistry` contract.
- [ ] Make sure `tag` was released for the new version of the package in order to be able to add the package as a dependency.
  ```
  git tag v{version}
  git push origin --tags
  ```
- [ ] Make sure that the `CHANGELOG` is updated with short description for the new version. 
### 7. Code review
- [ ] `resolver-keys.json` code review is required from **DevTools** team
- [ ] For all other changes code review is required from **Registry** team

2022-11-01 22:09 UTC, iurevych commented on resolver-keys.json
> +      "deprecatedKeyName": "0ZK",
Why `deprecatedKeyName`?

2022-11-02 17:19 UTC, dgrishajev commented on resolver-keys.json
> +      "deprecatedKeyName": "0ZK",
I'm not sure why it's `deprecatedKeyName,` but it seems that this key is used for every currency name in the `keys` collections.

Should it be called something else in this particular case?

2022-11-02 17:21 UTC, iurevych commented on resolver-keys.json
> +      "deprecatedKeyName": "0ZK",
Sorry false alarm, I confused this attribute with `deprecated` and thought you marked this record as deprecated.

2022-11-02 17:23 UTC, dgrishajev commented on resolver-keys.json
> +      "deprecatedKeyName": "0ZK",
NP :)

2022-11-02 17:52 UTC, iurevych requested changes
0xbeach.wallet domain already has these records, we cannot simply delete them.

2022-11-02 17:52 UTC, iurevych commented on resolver-keys.json
> -    "crypto.0ZK.version.ERC20.address": {
We cannot simply delete config options, since we already have domains with such records. Instead, mark these with `deprecated: true`

2022-11-03 19:53 UTC, dgrishajev commented on resolver-keys.json
> -    "crypto.0ZK.version.ERC20.address": {
I'm not sure if this is how it's supposed to work, but if I mark the first 3 options as deprecated, it results in this UI:

![Screenshot 2022-11-03 at 21 50 54](https://user-images.githubusercontent.com/10829201/199820515-e548c430-5740-44bd-b6bf-279a5a78ba5c.png)

Can we introduce a new optional field like `hidden` to distinguish between deprecated options and those that we simply want to hide on our website?

2022-11-03 19:55 UTC, dgrishajev commented on resolver-keys.json
> -    "crypto.0ZK.version.ERC20.address": {
I can also hide the `deprecated` options. We only have 2 of those currently ([XZC](https://github.com/unstoppabledomains/uns/blob/main/resolver-keys.json#L224) and [FET](https://github.com/unstoppabledomains/uns/blob/main/resolver-keys.json#L2169)) and they're not even shown as options or marked as deprecated on the webiste.

2022-11-04 21:30 UTC, iurevych commented on resolver-keys.json
> -    "crypto.0ZK.version.ERC20.address": {
Hiding deprecated records is something we should indeed do, but only if the user didn't use it. If the record has a value we should display it. This way 99.99999% of users will not see such deprecated records.

But here in the UNS config such records should be clearly marked as deprecated.

2022-11-04 21:31 UTC, iurevych approved these changes
👍

2022-11-07 18:11 UTC, dgrishajev commented on resolver-keys.json
> -    "crypto.0ZK.version.ERC20.address": {
Hey @iurevych, could you check this [tiny PR](https://github.com/unstoppabledomains/unstoppable-domains-website/pull/6251/files) in the website and confirm that I understood the approach correctly? It uses the uns version with the changes from this PR into `uns`.

2022-11-08 13:16 UTC, aquiladev commented on CHANGELOG.md
> +>>>>>>> main
🤔

2022-11-08 13:34 UTC, dgrishajev commented on CHANGELOG.md
> +>>>>>>> main
Removed, thanks for flagging

2022-11-08 13:45 UTC, dgrishajev commented on resolver-keys.json
> -    "crypto.0ZK.version.ERC20.address": {
Moving on with these changes

2022-11-08 14:10 UTC, merged