feat: add ens-resolver-keys.json
unstoppabledomains/uns pull request #306
Opened 2023-09-20 20:18 UTC by sammyluo

## PR Checklist

### 1. Contracts versioning
- [ ] Make sure that the `patch` version of the contracts is increased if changes have been made to the `UNSRegistry`, `MintingManager`, `ProxyReader`, `ENSCustody` contracts.
- [ ] Make sure that the `minor` version of the contracts is increased if breaking changes have been made to the `UNSRegistry`, `MintingManager`, `ProxyReader`, `ENSCustody` contracts. It includes changes of interfaces.
### 2. Contracts licensing
- [ ] Make sure that no **SPDX-License-Identifier** defined in contracts.
- [ ] Make sure that the **header** is added to the new contract files. 
  ```
  // @author Unstoppable Domains, Inc.
  // @date {Month} {Day}(ordinal), {Year}
  ```
### 3. Coverage
- [ ] Make sure that the coverage of contracts has not decreased and strive **100%**
### 4. Configs versioning
- [ ] Make sure that the version of `uns-config.json` is increased if changes have been made to the config.
- [ ] Make sure that the version of `ens-config.json` is increased if changes have been made to the config.
- [ ] Make sure that the version of `resolver-keys.json` is increased if changes have been made to the config.
### 5. Package versioning
- [ ] Make sure that the `patch` version of package is increased if valuable changes have been made to the package. It includes contracts update, configs update, etc.
- [ ] Make sure that the `major.minor` version of package is synced with version of `UNSRegistry` contract.
- [ ] Make sure that the `CHANGELOG` is updated with short description for the new version. 
### 6. Code review
- [ ] `resolver-keys.json` code review is required from **DevTools** team
- [ ] For all other changes code review is required from **Registry** team

2023-09-21 04:06 UTC, tunguyennnnn commented on ens-resolver-keys.json
> +      "validationRegex": "(?:RwxQ3jUs2BjKhseNX1em4msn2GyV5XAec[PQRSTUVWXYZabcdefghijkmnopqrstuvwxyz]|RwxQ3jUs2BjKhseNX1em4msn2GyV5XAe[defghijkmnopqrstuvwxyz][123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefgh
🤣 for real this regex?

2023-09-21 04:09 UTC, tunguyennnnn commented on ens-resolver-keys.json
> +    "contenthash.ipns": {
🤔 where is the contenthash.onions?

2023-09-21 04:12 UTC, tunguyennnnn commented on ens-resolver-keys.json
> +      "unsKey": "crypto.MATIC.version.ERC20.address",
🤔 why is this ERC20?

2023-09-21 04:12 UTC, tunguyennnnn commented on ens-resolver-keys.json
> +      "unsKey": "crypto.FTM.version.ERC20.address",
why is this ERC20?

2023-09-21 04:24 UTC, tunguyennnnn commented on ens-resolver-keys.json
> +      "unsKey": "crypto.MATIC.version.ERC20.address",
it should be "crypto.MATIC.version.MATIC.address" right?

2023-09-21 10:46 UTC, DeRain commented on scripts/generate_ens-resolver-keys.ts
> +    validationRegex: null,
We can remove default since it's a plain UTF8 string we don't want to allow user to set it

2023-09-21 10:46 UTC, DeRain commented on scripts/generate_ens-resolver-keys.ts
> +    validationRegex: null,
Please try to find regexes for contentype formats since it will simplify implementation for frontend significantly

2023-09-21 12:31 UTC, iurevych requested changes
Thanks for the config! As we think about the final usage of this config, it is important to keep it lightweight. Currently it weighs around 155KB which feels excessive for the website frontend.

The proposal is to only keep relevant known keys: ~125 supported address keys and a handful of frequently used text records, and abi + content-hash. https://github.com/ensdomains/ens-app-v3/blob/main/src/constants/textRecords.json + see a few other json configs they have there for social records and some other known records keys.

2023-09-26 03:22 UTC, sammyluo commented on ens-resolver-keys.json
> +      "validationRegex": null
Updated

2023-09-26 03:23 UTC, sammyluo commented on ens-resolver-keys.json
> +      "validationRegex": null
I filtered the legacy coins with the latest commit. Please check.

2023-09-26 03:23 UTC, sammyluo commented on ens-resolver-keys.json
> +      "symbol": "THETA",
Updated and filtered the legacy coins in the latest commit.

2023-09-26 03:24 UTC, sammyluo commented on scripts/generate_ens-resolver-keys.ts
> +    validationRegex: null,
Updated

2023-09-26 03:24 UTC, sammyluo commented on scripts/generate_ens-resolver-keys.ts
> +    validationRegex: null,
Updated

2023-09-26 03:24 UTC, sammyluo commented on scripts/generate_ens-resolver-keys.ts
> +    validationRegex: null,
Updated. Thanks for the guidance!

2023-09-26 03:25 UTC, sammyluo commented on ens-resolver-keys.json
> +      "unsKey": "crypto.FTM.version.ERC20.address",
We only map to corresponding ERC20 token

2023-09-26 03:25 UTC, sammyluo commented on ens-resolver-keys.json
> +      "unsKey": "crypto.MATIC.version.ERC20.address",
We only map to corresponding ERC20 token

2023-09-26 03:26 UTC, sammyluo commented on ens-resolver-keys.json
> +    "contenthash.ipns": {
Added. Thanks for pointing it out!

2023-09-27 15:46 UTC, iurevych approved these changes
👍 :shipit:

2023-09-27 18:17 UTC, tunguyennnnn approved these changes

2023-09-27 19:12 UTC, merged