[#180571086] Handle invalid Resolver in ProxyReader
unstoppabledomains/uns pull request #76
Opened 2022-01-13 10:52 UTC by hivtushok

https://www.pivotaltracker.com/story/show/180571086

2022-01-13 11:43 UTC, mvlabat commented on contracts/ProxyReader.sol
> +                } catch {}
Do we want to catch any errors? Is there a way to check that the rejection data is empty so we do nothing only in this case (otherwise throw the error again)?

2022-01-13 12:23 UTC, aquiladev commented
I would love to see tests for these changes

2022-01-13 13:12 UTC, bogdan approved these changes
Please add a test.

2022-01-14 12:27 UTC, bogdan approved these changes

2022-01-14 12:39 UTC, aquiladev requested changes
we need to change our approach or resolver's validation. 
- we need to use `isContract` check 
- tests should cover EOA as a resolver address
- tests should cover `0xdead` as a resolver address

2022-01-14 15:52 UTC, aquiladev approved these changes

2022-01-14 15:57 UTC, merged